steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/gcp-nbeats-components/nbeats_forecaster/nbeats_forecaster:latest', '.' ]
images:
- 'us-central1-docker.pkg.dev/gcp-nbeats-components/nbeats_forecaster/nbeats_forecaster:latest'